name: Hello World Workflow

on:
  push:
    branches:
      - master

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Say Hello
      run: echo "Hello, World!"
